apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: stash-service-secret
  namespace: linkpouch-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secret-store
    kind: ClusterSecretStore
  target:
    name: stash-service-secret
    creationPolicy: Owner
  data:
  - secretKey: SIGNATURE_MASTER_KEY
    remoteRef:
      key: 94d5d4ea-35c4-41ca-8380-b4060123021e
  - secretKey: INDEXER_CALLBACK_SECRET
    remoteRef:
      key: 53390898-854e-4e7d-8d77-b40601231922
