apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stash-service-secret
  namespace: linkpouch-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secret-store
    kind: ClusterSecretStore
  target:
    name: stash-service-secret
    creationPolicy: Owner
  data:
  - secretKey: SIGNATURE_MASTER_KEY
    remoteRef:
      key: 94d5d4ea-35c4-41ca-8380-b4060123021e
  - secretKey: INDEXER_CALLBACK_SECRET
    remoteRef:
      key: 53390898-854e-4e7d-8d77-b40601231922
  - secretKey: GITHUB_CLIENT_ID
    remoteRef:
      key: 7509117a-cccb-4401-9215-b40c0167b8bc
  - secretKey: GITHUB_CLIENT_SECRET
    remoteRef:
      key: a1699bc2-f6f3-4f35-b194-b40c0167e17a
  - secretKey: GOOGLE_CLIENT_ID
    remoteRef:
      key: 96907829-aca6-4b14-acf8-b40c0168f67a
  - secretKey: GOOGLE_CLIENT_SECRET
    remoteRef:
      key: ef79d673-ee0d-4066-9131-b40c016903d7
  - secretKey: DISCORD_CLIENT_ID
    remoteRef:
      key: 6dc9fdcb-b950-40fd-959e-b40c01697600
  - secretKey: DISCORD_CLIENT_SECRET
    remoteRef:
      key: afb630f4-569c-48b7-8b42-b40c0169b696
  - secretKey: TWITTER_CLIENT_ID
    remoteRef:
      key: e1a20e09-2293-425f-b65b-b40c016b9693
  - secretKey: TWITTER_CLIENT_SECRET
    remoteRef:
      key: ee068732-8114-4a95-8146-b40c016ba681
