apiVersion: v1
kind: Service
metadata:
  name: stash-service
  namespace: linkpouch-dev
  labels:
    app: stash-service
spec:
  selector:
    app: stash-service
  ports:
  - port: 80
    targetPort: 8080
  clusterIP: None
