apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: seaweedfs-secret
  namespace: linkpouch-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secret-store
    kind: ClusterSecretStore
  target:
    name: seaweedfs-secret
    creationPolicy: Owner
    template:
      data:
        indexer-access-key: "{{ .indexerAccessKey }}"
        indexer-secret-key: "{{ .indexerSecretKey }}"
        stash-access-key: "{{ .stashAccessKey }}"
        stash-secret-key: "{{ .stashSecretKey }}"
        s3-config.json: |
          {
            "identities": [
              {
                "name": "indexer",
                "credentials": [{"accessKey": "{{ .indexerAccessKey }}", "secretKey": "{{ .indexerSecretKey }}"}],
                "actions": ["Write", "Tagging"]
              },
              {
                "name": "stash-service",
                "credentials": [{"accessKey": "{{ .stashAccessKey }}", "secretKey": "{{ .stashSecretKey }}"}],
                "actions": ["Read", "List", "Delete"]
              }
            ]
          }
  data:
  - secretKey: indexerAccessKey
    remoteRef:
      key: 2990914a-08ce-4130-983c-b406012233a4
  - secretKey: indexerSecretKey
    remoteRef:
      key: b48a50e5-1c4e-4cf7-841a-b40601227b9a
  - secretKey: stashAccessKey
    remoteRef:
      key: 6ffed835-3da4-4cd6-8940-b40601240a89
  - secretKey: stashSecretKey
    remoteRef:
      key: e2ed976e-658f-4a3a-ba2a-b406012416e5
